chore: export JAVA_HOME

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -90,6 +90,17 @@ jobs:
             echo "The sfdx-cli installation could not be verified"
             exit 1
           fi
+      - name: Set JAVA_HOME for macos
+        shell: bash
+        run: |
+          export JAVA_HOME=/Users/runner/hostedtoolcache/Java_Zulu_jdk/11.0.20-8/x64
+          if [[ ((`echo $JAVA_HOME` == "/Users/runner/hostedtoolcache/Java_Zulu_jdk/11.0.20-8/x64"))]]
+          then
+            echo "JAVA_HOME is valid -" $JAVA_HOME
+          else
+            echo "The JAVA_HOME could not be verified"
+            exit 1
+          fi
       - name: Run headless test
         uses: coactions/setup-xvfb@b6b4fcfb9f5a895edadc3bc76318fae0ac17c8b3
         with:
