chore: add runners

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -32,71 +32,71 @@ on:
 
 jobs:
   build:
+    runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [macos-latest]
+        os: [macos-latest, windows-latest, ubuntu-latest]
         nodeVersion:
           - 16.15.1
         vscodeVersion:
           - stable
-    runs-on: ${{ matrix.os }}
     steps:
-        - name: Checkout
-          uses: actions/checkout@v3
-          with:
-            path: ./salesforcedx-vscode
-            ref: ${{ github.event.ref }}
-        - uses: actions/setup-node@v3
-          with:
-            node-version: ${{ matrix.nodeVersion }}
-            cache: npm
-            cache-dependency-path: |
-              salesforcedx-vscode/package-lock.json
-              salesforcedx-vscode-automation-tests/package-lock.json
-        - name: Clone automation tests
-          uses: actions/checkout@v3
-          with:
-            repository: forcedotcom/salesforcedx-vscode-automation-tests
-            path: salesforcedx-vscode-automation-tests
-            ref: ${{ inputs.automationBranch }}
-        - name: Install Extension Dependencies
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          path: ./salesforcedx-vscode
+          ref: ${{ github.event.ref }}
+      - uses: actions/setup-node@v3
+        with:
+          node-version: ${{ matrix.nodeVersion }}
+          cache: npm
+          cache-dependency-path: |
+            salesforcedx-vscode/package-lock.json
+            salesforcedx-vscode-automation-tests/package-lock.json
+      - name: Clone automation tests
+        uses: actions/checkout@v3
+        with:
+          repository: forcedotcom/salesforcedx-vscode-automation-tests
+          path: salesforcedx-vscode-automation-tests
+          ref: ${{ inputs.automationBranch }}
+      - name: Install Extension Dependencies
+        run: |
+          npm install
+          npm run compile
+        working-directory: salesforcedx-vscode
+      - name: Install Test Dependencies
+        run: |
+          npm install
+        working-directory: salesforcedx-vscode-automation-tests
+      - name: Install the SFDX CLI
+        run: npm install -g sfdx-cli
+      - name: Verify CLI
+        shell: bash
+        run: |
+          set -e
+          sfdx version
+          SFDX_CLI_VERSION=$(sfdx version)
+          if [[ ((`echo $SFDX_CLI_VERSION | grep -c "sfdx-cli/"` > 0))]]
+          then
+            echo "sfdx-cli installed -" $SFDX_CLI_VERSION
+          else
+            echo "The sfdx-cli installation could not be verified"
+            exit 1
+          fi
+      - name: Run headless test
+        uses: coactions/setup-xvfb@b6b4fcfb9f5a895edadc3bc76318fae0ac17c8b3
+        with:
           run: |
-            npm install
-            npm run compile
-          working-directory: salesforcedx-vscode
-        - name: Install Test Dependencies
-          run: |
-            npm install
+            npm run setup
+            npm run automation-tests
           working-directory: salesforcedx-vscode-automation-tests
-        - name: Install the SFDX CLI
-          run: npm install -g sfdx-cli
-        - name: Verify CLI
-          shell: bash
-          run: |
-            set -e
-            sfdx version
-            SFDX_CLI_VERSION=$(sfdx version)
-            if [[ ((`echo $SFDX_CLI_VERSION | grep -c "sfdx-cli/"` > 0))]]
-            then
-              echo "sfdx-cli installed -" $SFDX_CLI_VERSION
-            else
-              echo "The sfdx-cli installation could not be verified"
-              exit 1
-            fi
-        - name: Run headless test
-          uses: coactions/setup-xvfb@b6b4fcfb9f5a895edadc3bc76318fae0ac17c8b3
-          with:
-            run: |
-              npm run setup
-              npm run automation-tests
-            working-directory: salesforcedx-vscode-automation-tests
-          env:
-            VSCODE_VERSION: ${{ matrix.vscodeVersion }}
-            SPEC_FILES: ${{ inputs.specFiles || '*.e2e.ts' }}
-            SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL_E2E }}
-            ORG_ID: ${{ secrets.ORG_ID_E2E }}
-        - uses: actions/upload-artifact@v3
-          if: failure()
-          with:
-            name: screenshots
-            path: ./salesforcedx-vscode-automation-tests/screenshots
+        env:
+          VSCODE_VERSION: ${{ matrix.vscodeVersion }}
+          SPEC_FILES: ${{ inputs.specFiles || '*.e2e.ts' }}
+          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL_E2E }}
+          ORG_ID: ${{ secrets.ORG_ID_E2E }}
+      - uses: actions/upload-artifact@v3
+        if: failure()
+        with:
+          name: screenshots
+          path: ./salesforcedx-vscode-automation-tests/screenshots
