feat: run LSP E2E tests if the box is selected

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -12,13 +12,13 @@ on:
         required: false
         default: false
         type: boolean
-      apexDebuggerE2ETests:
-        description: 'Apex Debugger e2e Tests'
+      apexE2ETests:
+        description: 'Apex e2e Tests'
         required: false
         default: false
         type: boolean
-      miscellaneousE2ETests:
-        description: 'Miscellaneous e2e Tests'
+      coreE2ETests:
+        description: 'Core e2e Tests'
         required: false
         default: false
         type: boolean
@@ -57,63 +57,70 @@ jobs:
         vscodeVersion:
           - stable
     steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+      # - name: Checkout
+      #   uses: actions/checkout@v3
+      #   with:
+      #     path: ./salesforcedx-vscode
+      #     ref: ${{ github.event.ref }}
+      # - uses: actions/setup-node@v3
+      #   with:
+      #     node-version: ${{ matrix.nodeVersion }}
+      #     cache: npm
+      #     cache-dependency-path: |
+      #       salesforcedx-vscode/package-lock.json
+      #       salesforcedx-vscode-automation-tests/package-lock.json
+      # - name: Clone automation tests
+      #   uses: actions/checkout@v3
+      #   with:
+      #     repository: forcedotcom/salesforcedx-vscode-automation-tests
+      #     path: salesforcedx-vscode-automation-tests
+      #     ref: ${{ inputs.automationBranch }}
+      # - name: Install Extension Dependencies
+      #   run: |
+      #     npm install
+      #     npm run compile
+      #   working-directory: salesforcedx-vscode
+      # - name: Install Test Dependencies
+      #   run: |
+      #     npm install
+      #   working-directory: salesforcedx-vscode-automation-tests
+      # - name: Install the SFDX CLI
+      #   run: npm install -g sfdx-cli
+      # - name: Verify CLI
+      #   shell: bash
+      #   run: |
+      #     set -e
+      #     sfdx version
+      #     SFDX_CLI_VERSION=$(sfdx version)
+      #     if [[ ((`echo $SFDX_CLI_VERSION | grep -c "sfdx-cli/"` > 0))]]
+      #     then
+      #       echo "sfdx-cli installed -" $SFDX_CLI_VERSION
+      #     else
+      #       echo "The sfdx-cli installation could not be verified"
+      #       exit 1
+      #     fi
+      - name: Run LSP E2E tests if selected
+        if: ${{ inputs.lspE2ETests }}
+        uses: ./.github/workflows/lspE2E.yml
         with:
-          path: ./salesforcedx-vscode
-          ref: ${{ github.event.ref }}
-      - uses: actions/setup-node@v3
-        with:
-          node-version: ${{ matrix.nodeVersion }}
-          cache: npm
-          cache-dependency-path: |
-            salesforcedx-vscode/package-lock.json
-            salesforcedx-vscode-automation-tests/package-lock.json
-      - name: Clone automation tests
-        uses: actions/checkout@v3
-        with:
-          repository: forcedotcom/salesforcedx-vscode-automation-tests
-          path: salesforcedx-vscode-automation-tests
-          ref: ${{ inputs.automationBranch }}
-      - name: Install Extension Dependencies
-        run: |
-          npm install
-          npm run compile
-        working-directory: salesforcedx-vscode
-      - name: Install Test Dependencies
-        run: |
-          npm install
-        working-directory: salesforcedx-vscode-automation-tests
-      - name: Install the SFDX CLI
-        run: npm install -g sfdx-cli
-      - name: Verify CLI
-        shell: bash
-        run: |
-          set -e
-          sfdx version
-          SFDX_CLI_VERSION=$(sfdx version)
-          if [[ ((`echo $SFDX_CLI_VERSION | grep -c "sfdx-cli/"` > 0))]]
-          then
-            echo "sfdx-cli installed -" $SFDX_CLI_VERSION
-          else
-            echo "The sfdx-cli installation could not be verified"
-            exit 1
-          fi
-      - name: Run headless test
-        uses: coactions/setup-xvfb@b6b4fcfb9f5a895edadc3bc76318fae0ac17c8b3
-        with:
-          run: |
-            npm run setup
-            npm run automation-tests
-            echo 'specFiles = ' + ${{ inputs.specFiles }}
-          working-directory: salesforcedx-vscode-automation-tests
-        env:
-          VSCODE_VERSION: ${{ matrix.vscodeVersion }}
-          SPEC_FILES: ${{ inputs.specFiles || '*.e2e.ts' }}
-          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL_E2E }}
-          ORG_ID: ${{ secrets.ORG_ID_E2E }}
-      - uses: actions/upload-artifact@v3
-        if: failure()
-        with:
-          name: screenshots
-          path: ./salesforcedx-vscode-automation-tests/screenshots
+          workflow: 'lspE2E.yml'
+          run: echo 'lspE2E box selected'
+
+      # - name: Run headless test
+      #   uses: coactions/setup-xvfb@b6b4fcfb9f5a895edadc3bc76318fae0ac17c8b3
+      #   with:
+      #     run: |
+      #       npm run setup
+      #       npm run automation-tests
+      #       echo 'specFiles = ' + ${{ inputs.specFiles }}
+      #     working-directory: salesforcedx-vscode-automation-tests
+      #   env:
+      #     VSCODE_VERSION: ${{ matrix.vscodeVersion }}
+      #     SPEC_FILES: ${{ inputs.specFiles || '*.e2e.ts' }}
+      #     SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL_E2E }}
+      #     ORG_ID: ${{ secrets.ORG_ID_E2E }}
+      # - uses: actions/upload-artifact@v3
+      #   if: failure()
+      #   with:
+      #     name: screenshots
+      #     path: ./salesforcedx-vscode-automation-tests/screenshots
