fix: move checkbox checking to outside steps

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -46,65 +46,66 @@ on:
           - 'visualforceLsp.e2e.ts'
 
 jobs:
-  build:
-    runs-on: ${{ matrix.os }}
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [macos-latest, windows-latest, ubuntu-latest]
-        nodeVersion:
-          - 16.15.1
-        vscodeVersion:
-          - stable
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-        with:
-          path: ./salesforcedx-vscode
-          ref: ${{ github.event.ref }}
-      - uses: actions/setup-node@v3
-        with:
-          node-version: ${{ matrix.nodeVersion }}
-          cache: npm
-          cache-dependency-path: |
-            salesforcedx-vscode/package-lock.json
-            salesforcedx-vscode-automation-tests/package-lock.json
-      - name: Clone automation tests
-        uses: actions/checkout@v3
-        with:
-          repository: forcedotcom/salesforcedx-vscode-automation-tests
-          path: salesforcedx-vscode-automation-tests
-          ref: ${{ inputs.automationBranch }}
-      - name: Install Extension Dependencies
-        run: |
-          npm install
-          npm run compile
-        working-directory: salesforcedx-vscode
-      - name: Install Test Dependencies
-        run: |
-          npm install
-        working-directory: salesforcedx-vscode-automation-tests
-      - name: Install the SFDX CLI
-        run: npm install -g sfdx-cli
-      - name: Verify CLI
-        shell: bash
-        run: |
-          set -e
-          sfdx version
-          SFDX_CLI_VERSION=$(sfdx version)
-          if [[ ((`echo $SFDX_CLI_VERSION | grep -c "sfdx-cli/"` > 0))]]
-          then
-            echo "sfdx-cli installed -" $SFDX_CLI_VERSION
-          else
-            echo "The sfdx-cli installation could not be verified"
-            exit 1
-          fi
-      - name: Run LSP E2E tests if selected
-        if: ${{ inputs.lspE2ETests }}
-        uses: ./.github/workflows/lspE2E.yml
-        with:
-          workflow: 'e2e.yml'
-          run: echo 'lspE2E box selected'
+  # build:
+  #   runs-on: ${{ matrix.os }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os: [macos-latest, windows-latest, ubuntu-latest]
+  #       nodeVersion:
+  #         - 16.15.1
+  #       vscodeVersion:
+  #         - stable
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v3
+  #       with:
+  #         path: ./salesforcedx-vscode
+  #         ref: ${{ github.event.ref }}
+  #     - uses: actions/setup-node@v3
+  #       with:
+  #         node-version: ${{ matrix.nodeVersion }}
+  #         cache: npm
+  #         cache-dependency-path: |
+  #           salesforcedx-vscode/package-lock.json
+  #           salesforcedx-vscode-automation-tests/package-lock.json
+  #     - name: Clone automation tests
+  #       uses: actions/checkout@v3
+  #       with:
+  #         repository: forcedotcom/salesforcedx-vscode-automation-tests
+  #         path: salesforcedx-vscode-automation-tests
+  #         ref: ${{ inputs.automationBranch }}
+  #     - name: Install Extension Dependencies
+  #       run: |
+  #         npm install
+  #         npm run compile
+  #       working-directory: salesforcedx-vscode
+  #     - name: Install Test Dependencies
+  #       run: |
+  #         npm install
+  #       working-directory: salesforcedx-vscode-automation-tests
+  #     - name: Install the SFDX CLI
+  #       run: npm install -g sfdx-cli
+  #     - name: Verify CLI
+  #       shell: bash
+  #       run: |
+  #         set -e
+  #         sfdx version
+  #         SFDX_CLI_VERSION=$(sfdx version)
+  #         if [[ ((`echo $SFDX_CLI_VERSION | grep -c "sfdx-cli/"` > 0))]]
+  #         then
+  #           echo "sfdx-cli installed -" $SFDX_CLI_VERSION
+  #         else
+  #           echo "The sfdx-cli installation could not be verified"
+  #           exit 1
+  #         fi
+
+  Run_LSP_E2E_tests_if_selected:
+    if: ${{ always() }}
+    uses: ./.github/workflows/lspE2E.yml
+    with:
+      workflow: 'e2e.yml'
+      run: echo 'lspE2E box selected'
 
       # - name: Run headless test
       #   uses: coactions/setup-xvfb@b6b4fcfb9f5a895edadc3bc76318fae0ac17c8b3
