chore: use format

diff --git a/.github/workflows/e2ePerf.yml b/.github/workflows/e2ePerf.yml
--- a/.github/workflows/e2ePerf.yml
+++ b/.github/workflows/e2ePerf.yml
@@ -8,6 +8,17 @@ on:
         default: 'develop'
         type: string
 
+# all possible combinations of OS and architecture supported by yourkit
+env:
+  Linux-ARM: ./yourkit-distro/linux-arm-32/libyjpagent.so
+  Windows-X86: ./yourkit-distro/windows-x86-32/yjpagent.dll
+  Linux-X86: ./yourkit-distro/linux-x86-32/libyjpagent.so
+  Windows-X64: ./yourkit-distro/windows-x86-64/yjpagent.dll
+  Linux-ARM64: ./yourkit-distro/linux-arm-64/libyjpagent.so
+  macOs-X64: ./yourkit-distro/mac/libyjpagent.dylib
+  Windows-ARM64: ./yourkit-distro/windows-arm-64/yjpagent.dll
+  Linux-X64: ./yourkit-distro/linux-x86-64/libyjpagent.so
+
 jobs:
   build:
     strategy:
@@ -31,49 +42,38 @@ jobs:
           cache-dependency-path: |
             salesforcedx-vscode/package-lock.json
             salesforcedx-vscode-automation-tests/package-lock.json
-      # - name: Clone automation tests
-      #   uses: actions/checkout@v3
-      #   with:
-      #     repository: forcedotcom/salesforcedx-vscode-automation-tests
-      #     path: salesforcedx-vscode-automation-tests
-      #     ref: ${{ inputs.automationBranch }}
-      # - name: Install Extension Dependencies
-      #   run: |
-      #     npm install &&
-      #     npm run compile
-      #   working-directory: salesforcedx-vscode
-      # - name: Install Test Dependencies
-      #   run: |
-      #     npm install
-      #   working-directory: salesforcedx-vscode-automation-tests
-      # - name: Install the SFDX CLI
-      #   run: npm install -g sfdx-cli
-      # - name: Verify CLI
-      #   shell: bash
-      #   run: |
-      #     set -e
-      #     sfdx version
-      #     SFDX_CLI_VERSION=$(sfdx version)
-      #     if [[ ((`echo $SFDX_CLI_VERSION | grep -c "sfdx-cli/"` > 0))]]
-      #     then
-      #       echo "sfdx-cli installed -" $SFDX_CLI_VERSION
-      #     else
-      #       echo "The sfdx-cli installation could not be verified"
-      #       exit 1
-      #     fi
-      - name: Export Yourkit Agent libs
+      - name: Clone automation tests
+        uses: actions/checkout@v3
+        with:
+          repository: forcedotcom/salesforcedx-vscode-automation-tests
+          path: salesforcedx-vscode-automation-tests
+          ref: ${{ inputs.automationBranch }}
+      - name: Install Extension Dependencies
         run: |
-          echo "Linux_ARM=./yourkit-distro/linux-arm-32/libyjpagent.so"  >> $GITHUB_ENV &&
-          echo "Windows_X86=./yourkit-distro/windows-x86-32/yjpagent.dll" >> $GITHUB_ENV &&
-          echo "Linux_X86=./yourkit-distro/linux-x86-32/libyjpagent.so" >> $GITHUB_ENV &&
-          echo "Windows_X64=./yourkit-distro/windows-x86-64/yjpagent.dll" >> $GITHUB_ENV &&
-          echo "Linux_ARM64=./yourkit-distro/linux-arm-64/libyjpagent.so" >> $GITHUB_ENV &&
-          echo "macOs_X64=./yourkit-distro/mac/libyjpagent.dylib" >> $GITHUB_ENV &&
-          echo "Windows_ARM64=./yourkit-distro/windows-arm-64/yjpagent.dll" >> $GITHUB_ENV &&
-          echo "Linux_X64=./yourkit-distro/linux-x86-64/libyjpagent.so" >> $GITHUB_ENV
-      - name: Setup Yourkit Agent
+          npm install &&
+          npm run compile
+        working-directory: salesforcedx-vscode
+      - name: Install Test Dependencies
         run: |
-          echo "YOURKIT_PROFILER_AGENT=$${{env.RUNNER_OS}}_${{env.RUNNER_ARCH}}=sampling,async_sampling_cpu,app_name=apex_lsp,alloc_object_counting,onexit=memory,onexit=memory,onexit=snapshot,onexit=hprof,dir=./snapshots" >> $GITHUB_ENV
+          npm install
+        working-directory: salesforcedx-vscode-automation-tests
+      - name: Install the SFDX CLI
+        run: npm install -g sfdx-cli
+      - name: Verify CLI
+        shell: bash
+        run: |
+          set -e
+          sfdx version
+          SFDX_CLI_VERSION=$(sfdx version)
+          if [[ ((`echo $SFDX_CLI_VERSION | grep -c "sfdx-cli/"` > 0))]]
+          then
+            echo "sfdx-cli installed -" $SFDX_CLI_VERSION
+          else
+            echo "The sfdx-cli installation could not be verified"
+            exit 1
+          fi
+      - name: Setup YourKit Agent
+        run: echo "YOURKIT_PROFILER_AGENT=${{ env[format('{0}_{1}', format('{0}', runner.os), runner.arch)] }}=sampling,async_sampling_cpu,app_name=apex_lsp,alloc_object_counting,onexit=memory,onexit=memory,onexit=snapshot,onexit=hprof,dir=./snapshots" >> $GITHUB_ENV
       - name: Create Yourkit Snapshot directory
         run: mkdir snapshots
       - name: Verify YourKit
