chore: turn on tests

diff --git a/.github/workflows/e2ePerf.yml b/.github/workflows/e2ePerf.yml
--- a/.github/workflows/e2ePerf.yml
+++ b/.github/workflows/e2ePerf.yml
@@ -42,36 +42,36 @@ jobs:
           cache-dependency-path: |
             salesforcedx-vscode/package-lock.json
             salesforcedx-vscode-automation-tests/package-lock.json
-      # - name: Clone automation tests
-      #   uses: actions/checkout@v3
-      #   with:
-      #     repository: forcedotcom/salesforcedx-vscode-automation-tests
-      #     path: salesforcedx-vscode-automation-tests
-      #     ref: ${{ inputs.automationBranch }}
-      # - name: Install Extension Dependencies
-      #   run: |
-      #     npm install &&
-      #     npm run compile
-      #   working-directory: salesforcedx-vscode
-      # - name: Install Test Dependencies
-      #   run: |
-      #     npm install
-      #   working-directory: salesforcedx-vscode-automation-tests
-      # - name: Install the SFDX CLI
-      #   run: npm install -g sfdx-cli
-      # - name: Verify CLI
-      #   shell: bash
-      #   run: |
-      #     set -e
-      #     sfdx version
-      #     SFDX_CLI_VERSION=$(sfdx version)
-      #     if [[ ((`echo $SFDX_CLI_VERSION | grep -c "sfdx-cli/"` > 0))]]
-      #     then
-      #       echo "sfdx-cli installed -" $SFDX_CLI_VERSION
-      #     else
-      #       echo "The sfdx-cli installation could not be verified"
-      #       exit 1
-      #     fi
+      - name: Clone automation tests
+        uses: actions/checkout@v3
+        with:
+          repository: forcedotcom/salesforcedx-vscode-automation-tests
+          path: salesforcedx-vscode-automation-tests
+          ref: ${{ inputs.automationBranch }}
+      - name: Install Extension Dependencies
+        run: |
+          npm install &&
+          npm run compile
+        working-directory: salesforcedx-vscode
+      - name: Install Test Dependencies
+        run: |
+          npm install
+        working-directory: salesforcedx-vscode-automation-tests
+      - name: Install the SFDX CLI
+        run: npm install -g sfdx-cli
+      - name: Verify CLI
+        shell: bash
+        run: |
+          set -e
+          sfdx version
+          SFDX_CLI_VERSION=$(sfdx version)
+          if [[ ((`echo $SFDX_CLI_VERSION | grep -c "sfdx-cli/"` > 0))]]
+          then
+            echo "sfdx-cli installed -" $SFDX_CLI_VERSION
+          else
+            echo "The sfdx-cli installation could not be verified"
+            exit 1
+          fi
       - name: Setup YourKit Agent
         run: |
           echo "YOURKIT_PROFILER_AGENT=${{ env[format('{0}_{1}', runner.os, runner.arch)] }}=sampling,async_sampling_cpu,app_name=apex_lsp,alloc_object_counting,onexit=memory,onexit=memory,onexit=snapshot,onexit=hprof,dir=./snapshots" >> $GITHUB_ENV
@@ -79,13 +79,13 @@ jobs:
         run: mkdir snapshots
       - name: Verify YourKit
         run: env
-      # - name: Run headless test
-      #   uses: coactions/setup-xvfb@b6b4fcfb9f5a895edadc3bc76318fae0ac17c8b3
-      #   with:
-      #     run: npm run automation-tests
-      #     working-directory: salesforcedx-vscode-automation-tests
-      #   env:
-      #     VSCODE_VERSION: ${{ matrix.vscodeVersion }}
+      - name: Run headless test
+        uses: coactions/setup-xvfb@b6b4fcfb9f5a895edadc3bc76318fae0ac17c8b3
+        with:
+          run: npm run automation-tests
+          working-directory: salesforcedx-vscode-automation-tests
+        env:
+          VSCODE_VERSION: ${{ matrix.vscodeVersion }}
       - uses: actions/upload-artifact@v3
         with:
           name: yourkit-snapshot
