chore: try windows fix

diff --git a/.github/workflows/runE2ETest.yml b/.github/workflows/runE2ETest.yml
--- a/.github/workflows/runE2ETest.yml
+++ b/.github/workflows/runE2ETest.yml
@@ -80,23 +80,32 @@ jobs:
             sf version
             SF_CLI_VERSION=$(sf version)
 
-            if [ "${{ matrix.os }}" = "windows-latest" ]; then
-              powershell -Command "if ($env:SF_CLI_VERSION -match '@salesforce/cli/') { Write-Host '@salesforce/cli installed -' $env:SF_CLI_VERSION } else { Write-Error 'The @salesforce/cli installation could not be verified'; exit 1 }"
-            else
-              bash -c 'if [ "$(echo $SF_CLI_VERSION | grep -c "@salesforce/cli/")" -gt 0 ]; then
-                echo "@salesforce/cli installed -" $SF_CLI_VERSION
-              else
-                echo "The @salesforce/cli installation could not be verified"
-                exit 1
-              fi'
-            fi
-
-            # Set THROTTLE_FACTOR
-            if [ "${{ matrix.os }}" = "windows-latest" ]; then
-              powershell -Command "$env:THROTTLE_FACTOR=5; Add-Content -Path $env:GITHUB_ENV -Value 'THROTTLE_FACTOR=5'"
-            else
-              bash -c 'echo "THROTTLE_FACTOR=1" >> $GITHUB_ENV'
-            fi
+            # Use shell-specific commands for OS check
+            case "${{ matrix.os }}" in
+              "windows-latest")
+                powershell -Command "
+                  if ($env:SF_CLI_VERSION -match '@salesforce/cli/') {
+                    Write-Host '@salesforce/cli installed -' $env:SF_CLI_VERSION
+                  } else {
+                    Write-Error 'The @salesforce/cli installation could not be verified'
+                    exit 1
+                  }
+                  $env:THROTTLE_FACTOR=5
+                  Add-Content -Path $env:GITHUB_ENV -Value 'THROTTLE_FACTOR=5'
+                "
+                ;;
+              *)
+                bash -c '
+                  if [ "$(echo $SF_CLI_VERSION | grep -c "@salesforce/cli/")" -gt 0 ]; then
+                    echo "@salesforce/cli installed -" $SF_CLI_VERSION
+                  else
+                    echo "The @salesforce/cli installation could not be verified"
+                    exit 1
+                  fi
+                  echo "THROTTLE_FACTOR=1" >> $GITHUB_ENV
+                '
+                ;;
+            esac
 
             # Compile packages
             npm run compile
