chore: wip

diff --git a/.github/workflows/runE2ETest.yml b/.github/workflows/runE2ETest.yml
--- a/.github/workflows/runE2ETest.yml
+++ b/.github/workflows/runE2ETest.yml
@@ -56,8 +56,8 @@ jobs:
           command: |
             cd salesforcedx-vscode
 
-            # Clean extensions directory
-            rm -rf ./extensions
+            # clean project
+            npm run clean && npm install && npm run compile
 
             # Download extension vsixes
             mkdir ./extensions
@@ -77,15 +77,12 @@ jobs:
             sf version
             SF_CLI_VERSION=$(sf version)
 
-            if [ "${{ matrix.os }}" = "windows-latest" ]; then
-              powershell -Command "if ($SF_CLI_VERSION -match '@salesforce/cli/') { Write-Host '@salesforce/cli installed -' $SF_CLI_VERSION } else { Write-Host 'The @salesforce/cli installation could not be verified'; exit 1 }"
+            if [[ ((`echo $SF_CLI_VERSION | grep -c "@salesforce/cli/"` > 0))]]
+            then
+              echo "@salesforce/cli installed -" $SF_CLI_VERSION
             else
-              if [ "$(echo $SF_CLI_VERSION | grep -c "@salesforce/cli/")" -gt 0 ]; then
-                echo "@salesforce/cli installed -" $SF_CLI_VERSION
-              else
-                echo "The @salesforce/cli installation could not be verified"
-                exit 1
-              fi
+              echo "The @salesforce/cli installation could not be verified"
+              exit 1
             fi
 
             # Set THROTTLE_FACTOR
@@ -94,9 +91,6 @@ jobs:
             else
               echo "THROTTLE_FACTOR=1" >> $GITHUB_ENV
             fi
-
-            # Compile packages
-            npm run compile
 
             # Run headless test
             npm run gha-automation-tests --spec ${{ format('packages/salesforcedx-vscode-automation-tests/lib/test/specs/{0}', inputs.testToRun) }}
