chore: wip

diff --git a/.github/workflows/runE2ETest.yml b/.github/workflows/runE2ETest.yml
--- a/.github/workflows/runE2ETest.yml
+++ b/.github/workflows/runE2ETest.yml
@@ -81,7 +81,12 @@ jobs:
             SF_CLI_VERSION=$(sf version)
 
             if [ "${{ matrix.os }}" = "windows-latest" ]; then
-              powershell -Command "if ($SF_CLI_VERSION -match '@salesforce/cli/') { Write-Host '@salesforce/cli installed -' $SF_CLI_VERSION } else { Write-Host 'The @salesforce/cli installation could not be verified'; exit 1 }"
+              bash -c 'if [[ "$(echo $SF_CLI_VERSION | grep -c "@salesforce/cli/")" -gt 0 ]]; then
+                echo "@salesforce/cli installed -" $SF_CLI_VERSION
+              else
+                echo "The @salesforce/cli installation could not be verified"
+                exit 1
+              fi'
             else
               if [ "$(echo $SF_CLI_VERSION | grep -c "@salesforce/cli/")" -gt 0 ]; then
                 echo "@salesforce/cli installed -" $SF_CLI_VERSION
@@ -93,7 +98,7 @@ jobs:
 
             # Set THROTTLE_FACTOR
             if [ "${{ matrix.os }}" = "windows-latest" ]; then
-              echo "THROTTLE_FACTOR=5" >> $GITHUB_ENV
+              bash -c 'echo "THROTTLE_FACTOR=5" >> $GITHUB_ENV'
             else
               echo "THROTTLE_FACTOR=1" >> $GITHUB_ENV
             fi
